### ISSUE TITLE
Cannot get a simple example up and running

### ISSUE THREAD

**Issue by natethelen** [songzh96/homebridge-crestron-lts#5]
**Describe Your Problem:**

I have a brand new Homebridge installation that is connected to my Apple Home and has only the homebridge-crestron-lts plugin installed.  I am trying to get the simplest possible setup working so I can build from there

Crestron Info:
Only have 2 modules in program
1. HomeKit-Server
  a. IPAddr$: {Crestron Processor IP} (also tried Homebridge IP)
  b. Port: 50001d
  c. Lightbulb_OUT$
  d. Lightbulb_IN$
2. HomeKit-Lightbulb
  a. Lights_Status[1] (tied to fb of a particular light)
  b. Lights_On[1] (tied to 'on' button for same light)
  c. Lights_Off[1] (tied to 'off' button for same light)
  d. Lightbulb_IN$
  e. Lightbulb_OUT$

**Logs:**

Homebridge Logs:

[9/6/2022, 4:05:53 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /volume1/homebridge/node_modules --strict-plugin-resolution
[9/6/2022, 4:05:53 PM] [HB Supervisor] Started Homebridge v1.5.0 with PID: 29147
[9/6/2022, 4:05:53 PM] Loaded config.json with 0 accessories and 2 platforms.
[9/6/2022, 4:05:53 PM] Loaded 0 cached accessories from cachedAccessories.
[9/6/2022, 4:05:53 PM] ---
[9/6/2022, 4:05:53 PM] Loaded plugin: homebridge-crestron-lts@1.1.2
[9/6/2022, 4:05:53 PM] Registering platform 'homebridge-crestron-lts.HomebridgeCrestron'
[9/6/2022, 4:05:53 PM] ---
[9/6/2022, 4:05:53 PM] Loading 2 platforms...
[9/6/2022, 4:05:53 PM] [HomebridgeCrestron] Initializing HomebridgeCrestron platform...
[9/6/2022, 4:05:53 PM] TypeError: Cannot read properties of undefined (reading 'toString')
    at HomebridgePlatform.registerDevices (/volume1/homebridge/node_modules/homebridge-crestron-lts/src/platform.ts:215:72)
    at HomebridgePlatform.discoverDevices (/volume1/homebridge/node_modules/homebridge-crestron-lts/src/platform.ts:156:10)
    at HomebridgeAPI.<anonymous> (/volume1/homebridge/node_modules/homebridge-crestron-lts/src/platform.ts:68:12)
    at HomebridgeAPI.emit (node:events:527:28)
    at HomebridgeAPI.signalFinished (/volume1/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/volume1/homebridge/node_modules/homebridge/src/server.ts:190:14)
[9/6/2022, 4:05:53 PM] Got SIGTERM, shutting down Homebridge...
[9/6/2022, 4:05:58 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[9/6/2022, 4:06:03 PM] [HB Supervisor] Restarting Homebridge...

Crestron Logs:

Lights_Status[1]                              1
Lightbulb_OUT$                             Lightbulb:1:eventPowerState:1*

**Plugin Config:**

{
    "bridge": {
        "name": "Homebridge XXXX",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 51304,
        "pin": "XXX-XX-XXX",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "HomebridgeCrestron",
            "host": "{Crestron Processor IP}",
            "port": "50001",
            "Lightbulb": [
                {
                    "name": "Office Light"
                }
            ],
            "platform": "HomebridgeCrestron"
        }
    ]
}

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.1.2
* **Homebridge Version**: 1.5.0
* **Node.js Version**: v16.16.0
* **NPM Version**: Not finding this anywhere in Homebridge interface
* **Operating System**: Synology's Linux (DSM 7)

**Comment by songzh96** [comment]
Looks like an id is missing
{
“id”:1,
"name": "Office Light"
}
