### ISSUE TITLE
[HomebridgeCrestron] Child bridge process ended

### ISSUE THREAD

**Issue by DR7** [songzh96/homebridge-crestron-lts#7]
**Describe The Bug:**
Hello, I am not sure what is causing this error but I am running this plugin on Homebridge v1.4.0-beta.4
and I had it installed and had a green icon beside the power icon to cycle the child bridge, now the icon changed from red to yellow and the bridge connects and disconnects.

**To Reproduce:**
After this was working this seemed to happen when I changed in "Dimlight" name in settings to "Kitchen" and then saved?

I notice if I then change the name back to "Dimlight" in setttings and save and then use the "X" to delete it and save, I restart the child bridge and the status icon changes back to green? I look at status and now the plugin seems to have loaded again properly and is connected to the Crestron host?

    at HomebridgeAPI.emit (node:events:390:28)
    at HomebridgeAPI.signalFinished (C:\Users\Allen\AppData\Roaming\npm\node_modules\homebridge\src\api.ts:275:10)
    at ChildBridgeFork.startBridge (C:\Users\Allen\AppData\Roaming\npm\node_modules\homebridge\src\childBridgeFork.ts:173:14)
[11/9/2022, 2:05:23 AM] [HomebridgeCrestron] Child bridge process ended
[11/9/2022, 2:05:23 AM] [HomebridgeCrestron] Process Ended. Code: 1, Signal: null
[11/9/2022, 2:05:28 AM] [Homebridge UI] Changes to config.json saved.
[11/9/2022, 2:05:30 AM] [HomebridgeCrestron] Restarting Process...
[11/9/2022, 2:05:30 AM] [HomebridgeCrestron] Launched child bridge with PID 4552
[11/9/2022, 2:05:30 AM] Registering platform 'homebridge-crestron-lts.HomebridgeCrestron'
[11/9/2022, 2:05:30 AM] [HomebridgeCrestron] Loaded homebridge-crestron-lts v1.1.2 child bridge successfully
[11/9/2022, 2:05:30 AM] Homebridge v1.4.0-beta.4 (HAP v0.10.0-beta.7) (HomebridgeCrestron) is running on port 41899.
TypeError: Cannot read properties of undefined (reading 'toString')
    at HomebridgePlatform.registerDevices (C:\Users\Allen\AppData\Roaming\npm\node_modules\homebridge-crestron-lts\src\platform.ts:215:72)
    at HomebridgePlatform.discoverDevices (C:\Users\Allen\AppData\Roaming\npm\node_modules\homebridge-crestron-lts\src\platform.ts:157:10)
    at HomebridgeAPI.<anonymous> (C:\Users\Allen\AppData\Roaming\npm\node_modules\homebridge-crestron-lts\src\platform.ts:68:12)
    at HomebridgeAPI.emit (node:events:390:28)
    at HomebridgeAPI.signalFinished (C:\Users\Allen\AppData\Roaming\npm\node_modules\homebridge\src\api.ts:275:10)
    at ChildBridgeFork.startBridge (C:\Users\Allen\AppData\Roaming\npm\node_modules\homebridge\src\childBridgeFork.ts:173:14)
[11/9/2022, 2:05:30 AM] [HomebridgeCrestron] Child bridge process ended
[11/9/2022, 2:05:30 AM] [HomebridgeCrestron] Process Ended. Code: 1, Signal: null
[11/9/2022, 2:05:36 AM] [HomebridgeCrestron] Restarting child bridge...
[11/9/2022, 2:05:37 AM] [HomebridgeCrestron] Restarting Process...
[11/9/2022, 2:05:37 AM] [HomebridgeCrestron] Launched child bridge with PID 6724
[11/9/2022, 2:05:38 AM] Registering platform 'homebridge-crestron-lts.HomebridgeCrestron'
[11/9/2022, 2:05:38 AM] [HomebridgeCrestron] Loaded homebridge-crestron-lts v1.1.2 child bridge successfully
[11/9/2022, 2:05:38 AM] [HomebridgeCrestron]                                                               
[11/9/2022, 2:05:38 AM] [HomebridgeCrestron] **************************************************************
[11/9/2022, 2:05:38 AM] [HomebridgeCrestron]            homebridge-crestron v-1.0.0 By songzh96
[11/9/2022, 2:05:38 AM] [HomebridgeCrestron]   GitHub: https://github.com/songzh96/homebridge-crestron-ts  
[11/9/2022, 2:05:38 AM] [HomebridgeCrestron]                                          QQ Group: 107927710  
[11/9/2022, 2:05:38 AM] [HomebridgeCrestron] **************************************************************
[11/9/2022, 2:05:38 AM] [HomebridgeCrestron]                                                               
[11/9/2022, 2:05:38 AM] [HomebridgeCrestron] connect to 192.168.1.214:50001
[11/9/2022, 2:05:38 AM] Homebridge v1.4.0-beta.4 (HAP v0.10.0-beta.7) (HomebridgeCrestron) is running on port 41899.
[11/9/2022, 2:05:38 AM] [HomebridgeCrestron] connected to the host

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
{
    "name": "HomebridgeCrestron",
    "host": "192.168.1.214",
    "port": "50001",
    "DimLightbulb": [
        {
            "name": "DimLight"
        }
    ],
    "platform": "HomebridgeCrestron"
}
```

**Screenshots:**
[https://imgur.com/a/Sk8cuOt](Captures of the error)
**Environment:**

* **Plugin Version**: homebridge-crestron-lts v1.1.2
* **Homebridge Version**: v1.4.0-beta.4
* **Node.js Version**: v16.13.1
* **NPM Version**: 
* **Operating System**: Windows 10 Pro

**Comment by labazowie** [comment]
I have noticed the same problem on my side.
